swagger: "2.0"
info:
  title: Transactions API
  version: 1.0.0
host: localhost:3001
basePath: /api/v1
schemes:
  - https
  - http
tags:
  - name: Transactions
    description: Endpoints for managing user's transactions
paths:
  /user/transactions:
    get:
      tags:
        - Transactions
      summary: Retrieve all transactions for the current month
      parameters:
        - in: query
          name: month
          type: string
          description: The month for which to retrieve the transactions (the current month)
          default: "2023-08"
          required: true
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
      responses:
        200:
          description: List of transactions for the specified month
          schema:
            type: array
            items:
              $ref: "#/definitions/TransactionWithDetails"
        400:
          description: Invalid request
      security:
        - JWT: []

  /user/transactions/{transactionId}:
    get:
      tags:
        - Transactions
      summary: Retrieve details of a specific transaction
      parameters:
        - in: path
          name: transactionId
          type: string
          required: true
          description: Transaction identifier
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
      responses:
        200:
          description: Transaction details
          schema:
            $ref: "#/definitions/TransactionWithDetails"
        404:
          description: Transaction not found
        400:
          description: Invalid values
        500:
          description: Internal Server Error
      security:
        - JWT: []

    put:
      tags:
        - Transactions
      summary: Modify an existing transaction
      parameters:
        - in: path
          name: transactionId
          type: string
          required: true
          description: Transaction identifier
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
        - in: body
          name: details
          schema:
            $ref: "#/definitions/TransactionUpdate"
          required: true
      responses:
        200:
          description: Transaction successfully updated
          schema:
            $ref: "#/definitions/UpdatedTransactionWithDetails"
        400:
          description: Invalid request (incorrect transaction data)
        404:
          description: Transaction not found
        500:
          description: Internal Server Error
      security:
        - JWT: []

securityDefinitions:
  JWT:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier of the transaction
      month:
        type: string
        description: Month of the transaction
      date:
        type: string
        format: date
        description: Date of the transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: number
        format: float
        description: Amount of the transaction
      balance:
        type: number
        format: float
        description: Account balance after the transaction
    required:
      - date
      - description
      - amount
      - balance

  TransactionUpdate:
    type: object
    properties:
      transactionType:
        type: string
        description: Transaction type
      category:
        type: string
        description: Transaction category
      note:
        type: string
        description: User's notes for the transaction

  UpdatedTransaction:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier of the transaction
      month:
        type: string
        description: Month of the transaction
      date:
        type: string
        format: date
        description: Date of the transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: number
        format: float
        description: Amount of the transaction
      balance:
        type: number
        format: float
        description: Account balance after the transaction
      transactionType:
        type: string
        description: Transaction type
      category:
        type: string
        description: Updated transaction category
      note:
        type: string
        description: Updated user's notes for the transaction

  TransactionWithDetails:
    allOf:
      - $ref: "#/definitions/Transaction"
      - type: object
        properties:
          transactionType:
            type: string
            description: Transaction type
          category:
            type: string
            description: Transaction category
          note:
            type: string
            description: User's notes for the transaction

  UpdatedTransactionWithDetails:
    allOf:
      - $ref: "#/definitions/UpdatedTransaction"
      - type: object
        properties:
          id:
            type: string
            description: Unique identifier of the transaction
          month:
            type: string
            description: Month of the transaction
          date:
            type: string
            format: date
            description: Date of the transaction
          description:
            type: string
            description: Description of the transaction
          amount:
            type: number
            format: float
            description: Amount of the transaction
          balance:
            type: number
            format: float
            description: Account balance after the transaction
          transactionType:
            type: string
            description: Transaction type
          category:
            type: string
            description: Updated transaction category
          note:
            type: string
            description: Updated user's notes for the transaction
